networks:
  app-turistica-prod:
    name: app-turistica-prod

services:
  app-prod:
    image: webdevops/php-nginx:8.2
    container_name: app-prod
    restart: on-failure
    working_dir: /app
    ports:
      #- "94:80" #dev
      - "95:80" #prod
    volumes:
      - ./app:/app:rw
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    depends_on:
      - db-turistica-prod
    networks:
      - app-turistica-prod
  
  db-turistica-prod:
    image: mysql:8.0.28
    container_name: db-turistica-prod
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    volumes:
      - ./database/db:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: exito
      MYSQL_DATABASE: dbturisticaprod
    ports:
      #- "3320:3306" #dev
      - "3319:3306" #prod
    networks:
      - app-turistica-prod